# Generated by Django 5.2.4 on 2025-07-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
