# Generated by Django 5.2.4 on 2025-07-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_seller_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
    ]
