# Generated by Django 5.2.4 on 2025-07-21 19:29

import uuid
from django.db import migrations, models

def set_unique_ids(apps, schema_editor):
    Product = apps.get_model('seller', 'Product')
    for product in Product.objects.all():
        product.unique_id = uuid.uuid4()
        product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_product_image_product_order_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        # 1. Add the field as nullable and not unique
        migrations.AddField(
            model_name='product',
            name='unique_id',
            field=models.UUIDField(null=True, editable=False, db_index=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        # 2. Populate unique values for all existing products
        migrations.RunPython(set_unique_ids, reverse_code=migrations.RunPython.noop),
        # 3. Alter the field to be unique and non-nullable
        migrations.AlterField(
            model_name='product',
            name='unique_id',
            field=models.UUIDField(unique=True, editable=False, db_index=True),
        ),
    ]
