# Generated by Django 5.2.4 on 2025-07-21 20:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_remove_productimage_image_url_product_unique_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='is_primary',
            new_name='is_thumbnail',
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
