# Generated by Django 5.2.4 on 2025-07-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_rename_is_primary_productimage_is_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
