# Generated by Django 5.2.4 on 2025-07-27 01:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_placed', 'Order Placed'), ('order_updated', 'Order Updated'), ('order_delivered', 'Order Delivered'), ('payment_received', 'Payment Received'), ('product_added', 'Product Added'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('stock_low', 'Low Stock'), ('system', 'System')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_cleared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='seller.seller')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
