# Generated by Django 5.2.4 on 2025-07-28 03:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('promotion_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount'), ('buy_one_get_one', 'Buy One Get One'), ('free_shipping', 'Free Shipping')], default='percentage', max_length=20)),
                ('discount_value', models.FloatField(help_text='Percentage or fixed amount based on promotion type')),
                ('min_order_amount', models.FloatField(default=0, help_text='Minimum order amount to apply promotion')),
                ('max_discount_amount', models.FloatField(blank=True, help_text='Maximum discount amount (for percentage discounts)', null=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this promotion can be used', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='promotions', to='seller.category')),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='seller.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='seller.seller')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
