# Generated by Django 5.2.4 on 2025-07-29 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftBoxCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerGiftBoxParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='seller.giftboxcampaign')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftbox_participations', to='seller.seller')),
            ],
            options={
                'unique_together': {('seller', 'campaign')},
            },
        ),
    ]
