# Generated by Django 5.2.4 on 2025-08-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_alter_productreview_options_productreview_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerreview',
            name='rating',
            field=models.FloatField(blank=True, choices=[(0.0, 0.0), (0.5, 0.5), (1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0), (4.5, 4.5), (5.0, 5.0)], null=True),
        ),
    ]
