# Generated by Django 5.2.4 on 2025-07-22 22:04

from django.db import migrations, models

def clean_invalid_references(apps, schema_editor):
    ProductAttributeValue = apps.get_model('seller', 'ProductAttributeValue')
    Product = apps.get_model('seller', 'Product')
    
    # Get all valid product IDs
    valid_product_ids = set(Product.objects.values_list('id', flat=True))
    
    # Delete attribute values with invalid product references
    ProductAttributeValue.objects.exclude(product_id__in=valid_product_ids).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_initial'),
        ('seller', '0006_rename_is_primary_productimage_is_thumbnail_and_more'),
    ]

    operations = [
        # First clean up invalid references
        migrations.RunPython(clean_invalid_references, reverse_code=migrations.RunPython.noop),
        
        # Then add the new fields
        migrations.AddField(
            model_name='cart',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
