# Generated by Django 5.2.4 on 2025-07-24 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_cart_coupon_code_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='address',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='US', max_length=50)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='buyer.buyer')),
            ],
        ),
    ]
