# Generated by Django 5.2.4 on 2025-07-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_alter_order_options_order_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('stripe', 'Stripe')], default='cod', max_length=20),
        ),
    ]
