# Generated by Django 5.2.4 on 2025-07-27 01:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_order_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('stock', 'Low Stock'), ('price', 'Price Drop'), ('order', 'Order Update'), ('system', 'System')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='buyer.buyer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
