# Generated by Django 5.2.4 on 2025-07-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_giftboxorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftboxorder',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
