# Generated by Django 5.2.4 on 2025-08-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0010_buyer_address_buyer_date_of_birth_buyer_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftboxorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giftboxorder',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='giftboxorder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
