# Generated by Django 5.2.4 on 2025-08-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0011_giftboxorder_expected_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftboxorder',
            name='order_type',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('stripe', 'Stripe')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='giftboxorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
