# Generated by Django 5.2.4 on 2025-08-01 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0012_giftboxorder_order_type_giftboxorder_payment_status'),
        ('seller', '0012_giftboxcampaign_sellergiftboxparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftboxorder',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.promotion'),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.promotion'),
        ),
    ]
